name: danalysis
description: A library for exploring Dart analyzer and friends 
version: 0.0.1
repository: https://github.com/osaxma/danalysis

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  path: ^1.8.0
  analyzer: ^6.2.0
  dolumns: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
